### ISSUE TITLE
rules_rust is broken with Bazel@HEAD on Bazel CI 

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_rust#1938]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2975#0187b105-64ac-489a-9669-5422ef5841ae

Platform : rules_rust (Bzlmod Examples on :ubuntu: 20.04 LTS (OpenJDK 11, gcc 9.4.0))

```
(02:23:04) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/b66e34ecd9a320ebfcd56259c6d4c4ba/external/rules_rust~override/util/process_wrapper/BUILD.bazel:6:36: in rust_binary_without_process_wrapper rule @rules_rust~override//util/process_wrapper:process_wrapper:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/b66e34ecd9a320ebfcd56259c6d4c4ba/external/rules_rust~override/rust/private/rust.bzl", line 338, column 32, in _rust_binary_impl
  | return rustc_compile_action(
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/b66e34ecd9a320ebfcd56259c6d4c4ba/external/rules_rust~override/rust/private/rustc.bzl", line 1075, column 52, in rustc_compile_action
  | dep_info, build_info, linkstamps = collect_deps(
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/b66e34ecd9a320ebfcd56259c6d4c4ba/external/rules_rust~override/rust/private/rustc.bzl", line 232, column 65, in collect_deps
  | linkstamps.append(cc_info.linking_context.linkstamps())
  | Error in linkstamps: Rule in 'rust/private' cannot use private API

```

Steps followed
---------------
1. git clone -v https://github.com/bazelbuild/rules_rust.git
2. git reset f0e12c707ff85e05313d648a5be079d37e15edfc --hard
3. export USE_BAZEL_VERSION=bbf78a2cec27bf42bcbba59d3f84c857dff3aa15
4. bazel build //...

CC @meteorcloudy

**Comment by scentini** [comment]
@meteorcloudy I don't quite understand the culprit commit, but if it's of any help, `rules_rust` is exempted from the private API checks here https://github.com/bazelbuild/bazel/blob/3e140f374580f0f0eb5416872e9e421126920222/src/main/java/com/google/devtools/build/lib/rules/cpp/CcModule.java#L150. This does seem like something that needs to be fixed on the Bazel side, so I will not do further investigation.

**Comment by sgowroji** [comment]
Please ignore the above commit added in culprit. Edited and removed now. Thanks!

**Comment by buildbreaker2021** [comment]
I will take a look

**Comment by buildbreaker2021** [comment]
I could not reproduce this with neither currently released Bazel or with the one built at head. I fixed one bug internally earlier related to CopyBara transformation, which was causing the same [failure](https://www.google.com/url?sa=D&q=https%3A%2F%2Fbuildkite.com%2Fbazel%2Fbazel-at-head-plus-downstream%2Fbuilds%2F2908%230186de4c-24e3-471f-9a5a-76fb6c9e07fc) so I am assuming this version of Bazel was built at a bad change.

**Comment by meteorcloudy** [comment]
@buildbreaker2021 
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2982#0187bbbc-a5b6-4b00-b654-1987518b944b
still seeing the failure
```
Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/084f02f8944fe1c067dd3922f4639434/external/rules_rust~override/rust/private/rust.bzl", line 338, column 32, in _rust_binary_impl
		return rustc_compile_action(
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/084f02f8944fe1c067dd3922f4639434/external/rules_rust~override/rust/private/rustc.bzl", line 1075, column 52, in rustc_compile_action
		dep_info, build_info, linkstamps = collect_deps(
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/084f02f8944fe1c067dd3922f4639434/external/rules_rust~override/rust/private/rustc.bzl", line 232, column 65, in collect_deps
		linkstamps.append(cc_info.linking_context.linkstamps())
Error in linkstamps: Rule in 'rust/private' cannot use private API
```
in last night's downstream build.

Note that, this is failing with Bzlmod enabled, where the canonical name of rules_rust changed to `rules_rust~override`, I guess this is why the allowlist doesn't work? Is it possible to match `rules_rust*` instead?

**Comment by meteorcloudy** [comment]
From the code, it looks like it cannot match a pattern, however, is it possible to pass repo-mapping when creating the label from the allowlist here:
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/CcModule.java;l=2039
/cc @Wyverald

**Comment by meteorcloudy** [comment]
Repo mapping is available at https://cs.opensource.google/bazel/bazel/+/refs/heads/master:src/main/java/com/google/devtools/build/lib/cmdline/BazelModuleContext.java;l=39

**Comment by buildbreaker2021** [comment]
Will take another look.

> Note that, this is failing with Bzlmod enabled
I missed this thanks!

**Comment by meteorcloudy** [comment]
This failure has been fixed in https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2983, but there are other failures with rules_rust, will file new issues.
