### ISSUE TITLE
rules_rust is broken with Bazel@HEAD for windows platform

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_rust#1946]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2984#0187c5a7-a42b-4d14-904b-a6c46db44b21

Platform: windows

Logs :

```
LINK : fatal error LNK1181: cannot open input file 'windows.0.48.0.lib'
```
Reference : https://github.com/bazelbuild/rules_rust/issues/1938#issuecomment-1525552534

CC @meteorcloudy

**Comment by illicitonion** [comment]
Should be fixed by https://github.com/bazelbuild/rules_rust/pull/1944

**Comment by scentini** [comment]
Unfortunately I believe I didn't fix *all* the long paths; here's the one causing issues @HEAD:
`C:\\b\\pptrowys\\execroot\\examples\\bazel-out/x64_windows-opt-exec-ST-f007e4e0eadc/bin/vendor_local_pkgs/crates/windows_x86_64_msvc-0.48.0/windows_x86_64_msvc_build_script_.exe.runfiles/examples/vendor_local_pkgs/crates/windows_x86_64_msvc-0.48.0\\lib/windows.0.48.0.lib`
I could shorten the vendor_local_pkgs directory, but maybe one of you @illicitonion, @UebelAndre can point me to how to shorten windows_x86_64_msvc too?

**Comment by UebelAndre** [comment]
`windows_x86_64_msvc` is the name of a crate (https://crates.io/crates/windows_x86_64_msvc), shortening that would come with some complications. I would do `vendor_local_pkgs` for now.

**Comment by sgowroji** [comment]
Hi all, Gentle ping on this issue to know the latest update on it. Thanks!

**Comment by sgowroji** [comment]
Any update on this issue?

**Comment by sgowroji** [comment]
Hi @all, We will be moving this repo to Bazel Disabled CI pipeline. Will be moving back to downstream CI once the above  failure is fixed.

**Comment by illicitonion** [comment]
@sgowroji I've sent out https://github.com/bazelbuild/rules_rust/pull/2187 to stop running the broken tests - please hold off on disabling the whole ruleset :) Thanks!
