### ISSUE TITLE
Missing dependency causes breakage on Mac

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/rules_rust#20]
Breakage: http://ci.bazel.io/job/rules_rust/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/259/console

Reason: we now have sandbox on Mac, and the missing dependency cc_wrapper is not in the sandbox so we can't find it.

Suggested fix: add dependency //tools/defaults:crosstool to every rule that need gcc.

**Comment by davidzchen** [comment]
Fixed by #21

**Comment by damienmg** [comment]
Not yet fixed, apparently the input is not shiped into the sandbox but I just cannot debug it. --sandbox_debug has no effect.
