### ISSUE TITLE
bzlmod uses nightly by default

### ISSUE THREAD

**Issue by kitterion** [bazelbuild/rules_rust#2778]
I'm trying to migrate a project to bzlmod and I noticed that rust-analyzer has started complaining about
```
proc macro Deserialize not expanded: Cannot create expander for .../rules_rust~~crate~crate_index__serde_derive-1.0.196/libserde_derive-1588483640.so: mismatched ABI expected: rustc 1.79.0 (129f3b996 2024-06-10), got rustc 1.81.0-nightly (8337ba918 2024-06-12)
```
It turns out that everything is being built with a nightly compiler including proc macros, so rust-analyzer can't load them.

I can reproduce this in the [helloworld bzmod example](https://github.com/bazelbuild/rules_rust/tree/main/examples/bzlmod/hello_world). Trying to use a nightly feature in `src/main.rs` compiles while it shouldn't.

I did a little digging and I'm fairly certain this happens because the toolchains that are generated in the [toolchain hub](https://github.com/bazelbuild/rules_rust/blob/70e8729ce89056dea0033a98c14c74cc7f996b31/rust/private/repository_utils.bzl#L908) don't contain channel target settings unlike toolchains in the [proxy repo](https://github.com/bazelbuild/rules_rust/blob/70e8729ce89056dea0033a98c14c74cc7f996b31/rust/repositories.bzl#L638) that are used outside of bzlmod.

**Comment by archshift** [comment]
Any update on this? It's really unfortunate...

**Comment by UebelAndre** [comment]
I think this was addressed in https://github.com/bazelbuild/rules_rust/pull/3034 which released in [0.55.0](https://github.com/bazelbuild/rules_rust/releases/tag/0.55.0)

**Comment by archshift** [comment]
It still happens when using `rust.repository_set(...)` in bzlmod

**Comment by UebelAndre** [comment]
Those tags might need to plumb `channel` through. I don't see any reference to them so perhaps that's what's going on? I would actually expect this to be mandatory.

**Comment by illicitonion** [comment]
This looks like it was fixed at some point - I can no longer repro with the description in the initial report :) Please re-open if it's still a problem!
